sudo: required
services:
  - docker

before_install:
  - docker build -t hetpatel1506/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hetpatel1506/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-144489568283"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCES_KEY
  secret_access_key: "$AWS_SECRET_KEY"